github: Detect OP_GETH_BASE_BRANCH in update-geth workflow (#405)
* github: Detect OP_GETH_BASE_BRANCH in update-geth workflow

Minor additional changes:
* use a more informative job id than "job_id"
* add quotes to silence shellcheck warnings

Closes https://github.com/celo-org/celo-blockchain-planning/issues/933

* github: Fix ambiguous ls-remote match

The previous command yielded multiple results:
```
> git ls-remote https://github.com/celo-org/op-geth/ "celo-rebase-14"
18fdf55a858a46e5838c72f0e1eddcae00ced616	refs/heads/Kourin1996/celo-rebase-14
df2ea968968d4910ce21b44280a0077a54f73d3f	refs/heads/celo-rebase-14
```

That led to a malformed GITHUB_OUTPUT and caused job errors like
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'df2ea968968d4910ce21b44280a0077a54f73d3f'
```